"""Common utilities for Daikin Altherma 4 Modbus integration."""

from .helpers import (
    BaseEntityMixin,
    RegisterVersionDeviceInfoMixin,
    clamp_16bit,
    device_info_with_register_version,
    get_coordinator_from_entry,
    get_coordinator_register_data,
    get_register_config,
    get_register_scale,
    get_register_value,
    is_entity_available,
    is_unavailable_value,
    resolve_register_version,
    safe_write_register,
    to_signed_16bit,
    to_unsigned_16bit,
    update_value_if_changed,
    validate_register_value,
)

__all__ = [
    "BaseEntityMixin",
    "RegisterVersionDeviceInfoMixin",
    "clamp_16bit",
    "device_info_with_register_version",
    "get_coordinator_from_entry",
    "get_coordinator_register_data",
    "get_register_config",
    "get_register_scale",
    "get_register_value",
    "is_entity_available",
    "is_unavailable_value",
    "resolve_register_version",
    "safe_write_register",
    "to_signed_16bit",
    "to_unsigned_16bit",
    "update_value_if_changed",
    "validate_register_value",
]
